version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: weekly
    groups:
      npm-minor:
        update-types:
          - minor
          - patch
