name: Helm values.schema.json action
author: losisin
description: A GitHub action for generating json schema from multiple values files for Helm3 charts
inputs:
  input:
    description: Input value file. Can be single or comma-separated list of yaml files
    required: false
  draft:
    description: Draft version of the schema. Accepted values are 4, 6, 7, 2019 and 2020
    required: false
  indent:
    description: Indentation spaces (even number)
    required: false
  output:
    description: Output file name with path to store the generated schema
    required: false
  id:
    description: ID of the schema
    required: false
  title:
    description: Title of the schema
    required: false
  description:
    description: Description of the schema
    required: false
  additionalProperties:
    description: Additional properties allowed in the schema
    required: false
  git-push:
    description: If true it will commit and push the changes (ignored if `fail-on-diff` is set)
    required: false
    default: 'false'
  git-push-user-name:
    description: If empty the name of the GitHub Actions bot will be used (i.e. `github-actions[bot]`)
    required: false
    default: "github-actions[bot]"
  git-push-user-email:
    description: If empty the no-reply email of the GitHub Actions bot will be used (i.e. `github-actions[bot]@users.noreply.github.com`)
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  git-commit-message:
    description: Commit message
    required: false
    default: "update values.schema.json"
  fail-on-diff:
    description: Fail the job if there is any diff found between the generated output and existing file
    required: false
    default: false
  working-directory:
    description: 'Working directory where the schema command should run'
    required: false
  bundle:
    description: Bundle referenced (`$ref`) subschemas into a single file inside `$defs`
    required: false
    default: false
  bundle-root:
    description: Root directory to allow local referenced files to be loaded from
    required: false
    default: '.'
  bundle-without-id:
    description: Bundle without using `$id` to reference bundled schemas
    required: false
    default: false
  k8s-schema-version:
    description: Version used in the `--k8sSchemaURL` template for `$ref: $k8s/...` alias
    required: false
    default: 'v1.33.1'
  k8s-schema-url:
    description: URL template used in `$ref: $k8s/...` alias
    required: false
    type: string
    default: "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/{{ .K8sSchemaVersion }}/"
outputs:
   plugin-path:
      description: 'Path to the cached JSON schema binary'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: file-text
  color: gray-dark
