name: Helm values.schema.json action
author: losisin
description: A GitHub action for generating json schema from multiple values files for Helm3 charts. Uses helm plugin https://github.com/losisin/helm-values-schema-json

inputs:
  input:
    description: Input value file. Can be single or comma-separated list of yaml files
    required: true
  draft:
    description: Draft version of the schema. Accepted values are 4, 6, 7, 2019 and 2020
    required: false
    default: 2020
  output:
    description: Output file name with path to store the generated schema
    required: false
    default: values.schema.json
  git-push:
    description: If true it will commit and push the changes (ignored if `fail-on-diff` is set)
    required: false
    default: 'false'
  git-push-user-name:
    description: If empty the name of the GitHub Actions bot will be used (i.e. `github-actions[bot]`)
    required: false
    default: "github-actions[bot]"
  git-push-user-email:
    description: If empty the no-reply email of the GitHub Actions bot will be used (i.e. `github-actions[bot]@users.noreply.github.com`)
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  git-commit-message:
    description: Commit message
    required: false
    default: "update values.schema.json"
  fail-on-diff:
    description: Fail the job if there is any diff found between the generated output and existing file
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: file-text
  color: gray-dark
